version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork
  
networks:
  mynetwork:
    driver: bridge
volumes:
  db: