version: "2"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
  achat:
    image: springboot
    depends_on:
      - mysqldb
    container_name: springProject
    restart: on-failure
    ports:
      - 9001:9001
