version: "2"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_DATABASE=achatdb
    networks:
      - mynetwork
  achat:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    image: waelaissi/achat:latest
    ports:
      - 8090:8089
    volumes:
      - .m2:/root/.m2
    environment:
      SPRING_APPLICATION_JSON: '{
    "spring.datasource.url": "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
    "spring.datasource.username": "root",
    "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
    "spring.jpa.hibernate.ddl-auto": "update"
}'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  db: