ersion: "2"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
  achat:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    image: waelaissi/projet-achat:1.0
    ports:
      - 8090:8089
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: