version: "2"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=achatdb
  achat:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    image: spring-boot
    ports:
      - 8090:8089
    volumes:
      - .m2:/root/.m2
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
            "spring.datasource.username" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"}'
    stdin_open: true
    tty: true
volumes:
  db:
